[versions]
sa-token = "1.34.0"
commons-codec = "1.15"
commons-io = "2.12.0"

ktlint = "0.48.2"

junit5 = "5.8.1"
spock = "2.3-groovy-4.0"

[libraries]
saToken-spring = { module = "cn.dev33:sa-token-spring-boot3-starter", version.ref = "sa-token" }
saToken-jwt = { module = "cn.dev33:sa-token-jwt", version.ref = "sa-token" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }

junit5 = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
spock-spring = { module = "org.spockframework:spock-spring", version.ref = "spock" }

[bundles]
spock = ["spock-core", "spock-spring"]

[plugins]
