[versions]
kotlin = "1.9.23"

spring-boot = "3.2.2"

flyway = "9.22.3"

sa-token = "1.37.0"
commons-codec = "1.16.0"
commons-io = "2.15.0"

ktlint = "0.50.0"

junit5 = "5.10.1"
spock = "2.3-groovy-4.0"
ktor = "2.3.6"
jackson = "2.16.0"
logback = "1.4.11"

groovy = "4.0.15"

[libraries]
saToken-spring = { module = "cn.dev33:sa-token-spring-boot3-starter", version.ref = "sa-token" }
saToken-jwt = { module = "cn.dev33:sa-token-jwt", version.ref = "sa-token" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }

junit5 = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
spock-spring = { module = "org.spockframework:spock-spring", version.ref = "spock" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }

jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

groovy-all = { module = "org.apache.groovy:groovy-all", version.ref = "groovy" }

[bundles]
spock = ["spock-core", "spock-spring"]
jackson = ["jackson-module-kotlin", "jackson-databind", "jackson-core"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.4" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }

kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }

shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }

